=== ikeribisate/ejercicios-dtds-IkerIbisate/05_periodico/periodico.dtd
<!ELEMENT periodico (cabecera, portada, secciones+, contraportada)>

<!ELEMENT cabecera (nombre, fecha, edicion, numero, precio)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT edicion (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT precio (#PCDATA)>

<!ELEMENT portada (titular, noticias_d, publicidad)>
<!ELEMENT titular (#PCDATA)>
<!ELEMENT noticias_d (#PCDATA)>
<!ELEMENT publicidad (#PCDATA)>

<!ELEMENT secciones (noticias)>
<!ATTLIST secciones tipo (internacional|opinion|nacional|cultura|deportes|tv_radio) #REQUIRED>
<!ELEMENT noticias (titulo, subtitulo, entradilla, cuerpo)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT subtitulo (#PCDATA)>
<!ELEMENT entradilla (#PCDATA)>
<!ELEMENT cuerpo (#PCDATA)>

<!ELEMENT contraportada (#PCDATA)>

=== ikeribisate/ejercicios-dtds-IkerIbisate/05_periodico/periodico.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE periodico SYSTEM "periodico.dtd">


<periodico>
    <cabecera>
        <nombre></nombre>
        <fecha></fecha>
        <edicion></edicion>
        <numero></numero>
        <precio></precio>
    </cabecera>
    <portada>
        <titular></titular>
        <noticias_d></noticias_d>
        <publicidad></publicidad>
    </portada>
    <secciones tipo="tv_radio">
        <noticias>
            <titulo></titulo>
            <subtitulo></subtitulo>
            <entradilla></entradilla>
            <cuerpo></cuerpo>
        </noticias>
    </secciones>
    <contraportada></contraportada>
</periodico>
