=== ikeribisate/ejercicios-dtds-IkerIbisate/03_pedido/pedido.dtd
<!ELEMENT pedido (fecha, cuerpo_pedido, cliente)>

<!ELEMENT fecha (#PCDATA) >

<!ELEMENT cuerpo_pedido (articulo)>
<!ELEMENT articulo (nombre, tipo, unidades, precio)>
<!ATTLIST articulo id CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT unidades (#PCDATA)>
<!ELEMENT precio (#PCDATA)>

<!ELEMENT cliente (nombre, direccion_entrega, direccion_facturacion)>
<!ELEMENT direccion_entrega (nombre, calle, numero, cp, localidad, provincia)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT direccion_facturacion (calle, numero, localidad, provincia, cp)>

=== ikeribisate/ejercicios-dtds-IkerIbisate/03_pedido/pedido.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE pedido SYSTEM "pedido.dtd">
<pedido>
<fecha>2012/02/20</fecha>
<cuerpo_pedido>
  <articulo id="872-AA">
    <nombre>Cortadora de cesped</nombre>
    <tipo>electrica</tipo>
    <unidades>1</unidades>
    <precio>148.95</precio>
  </articulo>
  <articulo id="926-FH">
    <nombre>Podadora de setos</nombre>
    <tipo>?</tipo>
    <unidades>3</unidades>
    <precio>7.98</precio>
  </articulo>
</cuerpo_pedido>
<cliente>
  <nombre>Ricardo Movilla</nombre>
  <direccion_entrega>
    <nombre>In√©s Abad</nombre>
    <calle>Plaza de la Duquesa</calle>
    <numero>12</numero>
    <cp>31010</cp>
    <localidad>Pamplona</localidad>
    <provincia>Nafarroa</provincia>
  </direccion_entrega>
  <direccion_facturacion>
    <calle>Avenida de Gasteiz</calle>
    <numero>56</numero>
    <localidad>Vitoria-Gasteiz</localidad>
    <provincia>Araba</provincia>
    <cp>01012</cp>
  </direccion_facturacion>
</cliente>
</pedido>
