=== ikeribisate/ejercicios-dtds-IkerIbisate/02_agenda/agenda.dtd
<!ELEMENT agenda (contacto)+>
<!ELEMENT contacto (nombre, direccion, ciudad, codigo_postal,numeros, email, web, compania)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>
<!ELEMENT numeros (telefono,fax)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!ELEMENT compania (#PCDATA)>

<!ELEMENT telefono (#PCDATA)>
<!ELEMENT fax (#PCDATA)>

=== ikeribisate/ejercicios-dtds-IkerIbisate/02_agenda/agenda.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">
<agenda>
    <contacto>
        <nombre></nombre>
        <direccion></direccion>
        <ciudad></ciudad>
        <codigo_postal></codigo_postal>
        <numeros>
            <telefono></telefono>
            <fax></fax>
        </numeros>
        <email></email>
        <web></web>
        <compania></compania>
    </contacto>
</agenda>
