=== ikeribisate/ejercicios-dtds-IkerIbisate/08_universidad/universidad.dtd
<!ELEMENT universidad (alumnos,profesores)>

<!ELEMENT alumnos (dni, pasaporte?, nombre, apellidos,fecha_nacimiento,info_contacto)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT pasaporte (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT fecha_nacimiento (#PCDATA)>
<!ELEMENT info_contacto (dp,tlf,cuenta_correo)>
<!ELEMENT dp (#PCDATA)>
<!ELEMENT tlf (#PCDATA)>
<!ELEMENT cuenta_correo (#PCDATA)>


<!ELEMENT profesores (dni, pasaporte?, nombre, apellidos,fecha_nacimiento,info_contacto)>

=== ikeribisate/ejercicios-dtds-IkerIbisate/08_universidad/universidad.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE universidad SYSTEM "universidad.dtd">
<universidad>
    <alumnos>
        <dni></dni>
        <nombre></nombre>
        <apellidos></apellidos>
        <fecha_nacimiento></fecha_nacimiento>
    </alumnos>
    <profesores>
        <dni></dni>
        <nombre></nombre>
        <apellidos></apellidos>
        <fecha_nacimiento></fecha_nacimiento>
    </profesores>
</universidad>
